import {
  CLIENT_BROWSER_INVOKE,
  CLIENT_CONFIRM_DIALOG,
  CLIENT_OPEN_EXTERNAL,
  CLIENT_OPEN_FILE_DIALOG,
  CLIENT_OPEN_PATH,
  CLIENT_ROUTE_WORKSPACE_MARKER_DETACH,
  CLIENT_SHOW_IN_FOLDER,
} from '@mortise/server-core/transport'
import {
  BACKEND_TYPE_CAPABILITY,
  CLIENT_WORKSPACE_EXECUTE_TRANSFER,
} from '@mortise/shared/protocol'

const ELECTRON_BASE_CLIENT_CAPABILITIES = [
  CLIENT_OPEN_EXTERNAL,
  CLIENT_OPEN_PATH,
  CLIENT_SHOW_IN_FOLDER,
  CLIENT_CONFIRM_DIALOG,
  CLIENT_OPEN_FILE_DIALOG,
  CLIENT_BROWSER_INVOKE,
  BACKEND_TYPE_CAPABILITY.electron,
] as const

export function getElectronClientCapabilities(clientOnly: boolean): string[] {
  return [
    ...ELECTRON_BASE_CLIENT_CAPABILITIES,
    ...(!clientOnly
      ? [CLIENT_WORKSPACE_EXECUTE_TRANSFER, CLIENT_ROUTE_WORKSPACE_MARKER_DETACH]
      : []),
  ]
}
