import { type AgentMessage, uuidv7 } from "@mortise/pi-agent-core";
import type { ImageContent, Message, TextContent, Usage } from "@mortise/pi-ai/types";
import { createHash, randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	createReadStream,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	readSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "fs";
import { access, mkdir, open, readdir, readFile, rename, rm, stat, writeFile } from "fs/promises";
import { join, resolve } from "path";
import lockfile from "proper-lockfile";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
	/**
	 * Parent session ID for Mortise-owned child tasks created through RPC runtime opening.
	 * Unlike parentSession (which stores a file path), this stores the parent's
	 * session ID so the mortise shell can read back the spawn lineage.
	 */
	spawnedFrom?: string;
	/**
	 * Override config recorded at spawn time, for mortise shell to read back when
	 * loading the spawned child session. Only present on spawnChildSession-created
	 * children.
	 */
	spawnConfig?: {
		connection?: string;
		model?: string;
		enabledSources?: string[];
		thinkingLevel?: string;
		extensionBootstrap?: Record<string, Record<string, unknown>>;
		template?: string;
		systemPrompt?: string;
		tools?: string[];
		background?: boolean;
		backgroundOperationId?: string;
	};
	/**
	 * Opaque host-shell metadata. Pi preserves this object but does not interpret
	 * it; host facades update it through SessionManager so shells do not rewrite
	 * JSONL headers directly.
	 */
	mortise?: Record<string, unknown>;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
	/** Parent Agent Session ID for a Mortise-owned subagent task. */
	spawnedFrom?: string;
	/** Host-selected execution overrides retained with a subagent task. */
	spawnConfig?: SessionHeader["spawnConfig"];
	/** Stable creation time for explicit import/fixture materialization. */
	timestamp?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	summaryStats?: {
		durationMs: number;
		usage?: Usage;
		calls?: Array<{
			purpose: "history" | "turnPrefix";
			durationMs: number;
			usage?: Usage;
		}>;
	};
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export interface ChildSessionInfo extends SessionInfo {
	spawnedFrom: string;
	spawnConfig?: SessionHeader["spawnConfig"];
	parentSessionPath?: string;
	status: "completed" | "interrupted" | "failed";
	lastOutput?: string;
	persistedClientMutationIds: string[];
	history: Array<{
		role: string;
		text: string;
		timestamp?: number;
		stopReason?: string;
		clientMutationId?: string;
	}>;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.unshift(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}

	// Extract settings and find compaction
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];

	const appendMessage = (entry: SessionEntry) => {
		if (entry.type === "message") {
			messages.push(entry.message);
		} else if (entry.type === "custom_message") {
			messages.push(
				createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp),
			);
		} else if (entry.type === "branch_summary" && entry.summary) {
			messages.push(createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp));
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp));

		// Find compaction index in path
		const compactionIdx = path.findIndex((e) => e.type === "compaction" && e.id === compaction.id);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (entry.id === compaction.firstKeptEntryId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_CACHE_VERSION = 1;
const SESSION_READ_BUFFER_SIZE = 1024 * 1024;
const SESSION_TAIL_READ_BUFFER_SIZE = 64 * 1024;
const SESSION_ENTRY_CACHE_MAX_FILE_BYTES = 8 * 1024 * 1024;
const SESSION_FILE_LOCK_STALE_MS = 30_000;
const SESSION_FILE_LOCK_RETRY_DELAY_MS = 25;
const SESSION_FILE_LOCK_RETRY_COUNT = 1_400;
const SESSION_FILE_LOCK_SLEEP_BUFFER = new Int32Array(new SharedArrayBuffer(4));
const SESSION_WRITE_BATCH_BYTES = 256 * 1024;
export const SESSION_PERSISTENCE_MAX_PENDING_ENTRIES = 1_024;
const sessionEntriesMemoryCache = new Map<
	string,
	{ sourceMtimeMs: number; sourceSize: number; entries: FileEntry[] }
>();

interface CachedSessionEntriesPayload {
	version: typeof SESSION_CACHE_VERSION;
	sourcePath: string;
	sourceMtimeMs: number;
	sourceSize: number;
	entries: FileEntry[];
}

interface CachedSessionInfoPayload {
	version: typeof SESSION_CACHE_VERSION;
	sourcePath: string;
	sourceMtimeMs: number;
	sourceSize: number;
	sessionInfo: {
		path: string;
		id: string;
		cwd: string;
		name?: string;
		parentSessionPath?: string;
		created: string;
		modified: string;
		messageCount: number;
		firstMessage: string;
		allMessagesText: string;
	};
}

function hashSessionCacheKey(filePath: string): string {
	return createHash("sha1").update(normalizePath(filePath)).digest("hex");
}

function getSessionCacheRoot(agentDir: string = getDefaultAgentDir()): string {
	return join(resolvePath(agentDir), ".cache", "session-manager");
}

function getSessionEntriesCachePath(filePath: string, agentDir: string = getDefaultAgentDir()): string {
	return join(getSessionCacheRoot(agentDir), "entries", `${hashSessionCacheKey(filePath)}.json`);
}

function getSessionInfoCachePath(filePath: string, agentDir: string = getDefaultAgentDir()): string {
	return join(getSessionCacheRoot(agentDir), "info", `${hashSessionCacheKey(filePath)}.json`);
}

function hasValidSessionHeader(entries: FileEntry[]): boolean {
	if (entries.length === 0) return true;
	const header = entries[0];
	return header.type === "session" && typeof (header as { id?: unknown }).id === "string";
}

function writeCacheFileSync(filePath: string, content: string): void {
	mkdirSync(resolve(filePath, ".."), { recursive: true });
	const tempPath = `${filePath}.${process.pid}.${Date.now()}.${randomUUID().slice(0, 8)}.tmp`;
	writeFileSync(tempPath, content, "utf-8");
	try {
		renameSync(tempPath, filePath);
	} catch (error) {
		rmSync(tempPath, { force: true });
		throw error;
	}
}

async function writeCacheFile(filePath: string, content: string): Promise<void> {
	await mkdir(resolve(filePath, ".."), { recursive: true });
	const tempPath = `${filePath}.${process.pid}.${Date.now()}.${randomUUID().slice(0, 8)}.tmp`;
	await writeFile(tempPath, content, "utf-8");
	try {
		renameSync(tempPath, filePath);
	} catch (error) {
		rmSync(tempPath, { force: true });
		throw error;
	}
}

function readCachedSessionEntries(
	resolvedFilePath: string,
	sourceMtimeMs: number,
	sourceSize: number,
): FileEntry[] | undefined {
	const memory = sessionEntriesMemoryCache.get(resolvedFilePath);
	if (memory && memory.sourceMtimeMs === sourceMtimeMs && memory.sourceSize === sourceSize) {
		return memory.entries;
	}
	if (sourceSize > SESSION_ENTRY_CACHE_MAX_FILE_BYTES) {
		return undefined;
	}
	const cachePath = getSessionEntriesCachePath(resolvedFilePath);
	if (!existsSync(cachePath)) {
		return undefined;
	}
	try {
		const payload = JSON.parse(readFileSync(cachePath, "utf-8")) as CachedSessionEntriesPayload;
		if (
			payload.version !== SESSION_CACHE_VERSION ||
			payload.sourcePath !== resolvedFilePath ||
			payload.sourceMtimeMs !== sourceMtimeMs ||
			payload.sourceSize !== sourceSize ||
			!Array.isArray(payload.entries) ||
			!hasValidSessionHeader(payload.entries)
		) {
			return undefined;
		}
		sessionEntriesMemoryCache.set(resolvedFilePath, {
			sourceMtimeMs,
			sourceSize,
			entries: payload.entries,
		});
		return payload.entries;
	} catch {
		return undefined;
	}
}

function writeSessionEntriesCache(
	resolvedFilePath: string,
	sourceMtimeMs: number,
	sourceSize: number,
	entries: FileEntry[],
): void {
	if (sourceSize > SESSION_ENTRY_CACHE_MAX_FILE_BYTES || !hasValidSessionHeader(entries)) {
		return;
	}
	sessionEntriesMemoryCache.set(resolvedFilePath, { sourceMtimeMs, sourceSize, entries });
	const payload: CachedSessionEntriesPayload = {
		version: SESSION_CACHE_VERSION,
		sourcePath: resolvedFilePath,
		sourceMtimeMs,
		sourceSize,
		entries,
	};
	try {
		writeCacheFileSync(getSessionEntriesCachePath(resolvedFilePath), `${JSON.stringify(payload)}\n`);
	} catch {
		// Cache writes must not block session loading.
	}
}

function serializeSessionInfo(info: SessionInfo): CachedSessionInfoPayload["sessionInfo"] {
	return {
		path: info.path,
		id: info.id,
		cwd: info.cwd,
		name: info.name,
		parentSessionPath: info.parentSessionPath,
		created: info.created.toISOString(),
		modified: info.modified.toISOString(),
		messageCount: info.messageCount,
		firstMessage: info.firstMessage,
		allMessagesText: info.allMessagesText,
	};
}

function deserializeSessionInfo(serialized: CachedSessionInfoPayload["sessionInfo"]): SessionInfo {
	return {
		path: serialized.path,
		id: serialized.id,
		cwd: serialized.cwd,
		name: serialized.name,
		parentSessionPath: serialized.parentSessionPath,
		created: new Date(serialized.created),
		modified: new Date(serialized.modified),
		messageCount: serialized.messageCount,
		firstMessage: serialized.firstMessage,
		allMessagesText: serialized.allMessagesText,
	};
}

async function readCachedSessionInfo(
	resolvedFilePath: string,
	sourceMtimeMs: number,
	sourceSize: number,
): Promise<SessionInfo | undefined> {
	const cachePath = getSessionInfoCachePath(resolvedFilePath);
	try {
		const payload = JSON.parse(await readFile(cachePath, "utf-8")) as CachedSessionInfoPayload;
		if (
			payload.version !== SESSION_CACHE_VERSION ||
			payload.sourcePath !== resolvedFilePath ||
			payload.sourceMtimeMs !== sourceMtimeMs ||
			payload.sourceSize !== sourceSize
		) {
			return undefined;
		}
		return deserializeSessionInfo(payload.sessionInfo);
	} catch {
		return undefined;
	}
}

async function writeSessionInfoCache(
	resolvedFilePath: string,
	sourceMtimeMs: number,
	sourceSize: number,
	info: SessionInfo,
): Promise<void> {
	const payload: CachedSessionInfoPayload = {
		version: SESSION_CACHE_VERSION,
		sourcePath: resolvedFilePath,
		sourceMtimeMs,
		sourceSize,
		sessionInfo: serializeSessionInfo(info),
	};
	try {
		await writeCacheFile(getSessionInfoCachePath(resolvedFilePath), `${JSON.stringify(payload)}\n`);
	} catch {
		// Cache writes must not block session listing.
	}
}

function sleepSync(ms: number): void {
	Atomics.wait(SESSION_FILE_LOCK_SLEEP_BUFFER, 0, 0, ms);
}

function isLockConflict(error: unknown): boolean {
	return (
		typeof error === "object" &&
		error !== null &&
		"code" in error &&
		String((error as { code?: unknown }).code) === "ELOCKED"
	);
}

function acquireSessionFileLockSync(sessionFile: string): () => void {
	let lastError: unknown;
	for (let attempt = 1; attempt <= SESSION_FILE_LOCK_RETRY_COUNT; attempt++) {
		try {
			return lockfile.lockSync(sessionFile, { realpath: false, stale: SESSION_FILE_LOCK_STALE_MS });
		} catch (error) {
			if (!isLockConflict(error) || attempt === SESSION_FILE_LOCK_RETRY_COUNT) {
				throw error;
			}
			lastError = error;
			sleepSync(SESSION_FILE_LOCK_RETRY_DELAY_MS);
		}
	}
	throw (lastError as Error) ?? new Error(`Failed to acquire session file lock: ${sessionFile}`);
}

async function acquireSessionFileLock(sessionFile: string): Promise<() => Promise<void>> {
	let lastError: unknown;
	for (let attempt = 1; attempt <= SESSION_FILE_LOCK_RETRY_COUNT; attempt++) {
		try {
			return await lockfile.lock(sessionFile, { realpath: false, stale: SESSION_FILE_LOCK_STALE_MS });
		} catch (error) {
			if (!isLockConflict(error) || attempt === SESSION_FILE_LOCK_RETRY_COUNT) {
				throw error;
			}
			lastError = error;
			await new Promise<void>((resolveDelay) => setTimeout(resolveDelay, SESSION_FILE_LOCK_RETRY_DELAY_MS));
		}
	}
	throw (lastError as Error) ?? new Error(`Failed to acquire session file lock: ${sessionFile}`);
}

function writeEntriesAtomically(filePath: string, entries: FileEntry[]): void {
	const tempPath = `${filePath}.${process.pid}.${Date.now()}.${randomUUID().slice(0, 8)}.tmp`;
	const fd = openSync(tempPath, "wx");
	try {
		for (const entry of entries) {
			writeFileSync(fd, `${JSON.stringify(entry)}\n`);
		}
	} catch (error) {
		try {
			closeSync(fd);
		} catch {}
		rmSync(tempPath, { force: true });
		throw error;
	}
	closeSync(fd);
	try {
		renameSync(tempPath, filePath);
	} catch (error) {
		rmSync(tempPath, { force: true });
		throw error;
	}
}

async function pathExists(filePath: string): Promise<boolean> {
	try {
		await access(filePath);
		return true;
	} catch {
		return false;
	}
}

async function writeEntriesAtomicallyAsync(filePath: string, entries: FileEntry[], entryCount: number): Promise<void> {
	const tempPath = `${filePath}.${process.pid}.${Date.now()}.${randomUUID().slice(0, 8)}.tmp`;
	const handle = await open(tempPath, "wx");
	try {
		await writeEntryRange(handle, entries, 0, entryCount);
		await handle.close();
		await rename(tempPath, filePath);
	} catch (error) {
		await handle.close().catch(() => {});
		await rm(tempPath, { force: true }).catch(() => {});
		throw error;
	}
}

async function writeEntryRange(
	handle: Awaited<ReturnType<typeof open>>,
	entries: FileEntry[],
	startIndex: number,
	entryCount: number,
): Promise<void> {
	let batch = "";
	let batchBytes = 0;
	for (let index = startIndex; index < entryCount; index++) {
		const line = `${JSON.stringify(entries[index])}\n`;
		const lineBytes = Buffer.byteLength(line);
		if (batchBytes > 0 && batchBytes + lineBytes > SESSION_WRITE_BATCH_BYTES) {
			await handle.writeFile(batch);
			batch = "";
			batchBytes = 0;
		}
		batch += line;
		batchBytes += lineBytes;
	}
	if (batchBytes > 0) {
		await handle.writeFile(batch);
	}
}

async function appendEntriesAsync(
	filePath: string,
	entries: FileEntry[],
	startIndex: number,
	entryCount: number,
): Promise<void> {
	const handle = await open(filePath, "a");
	try {
		await writeEntryRange(handle, entries, startIndex, entryCount);
	} finally {
		await handle.close();
	}
}

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		return JSON.parse(line) as FileEntry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

async function loadEntriesFromFileAsync(filePath: string): Promise<FileEntry[]> {
	const content = await readFile(filePath, "utf8");
	return content
		.split("\n")
		.map(parseSessionEntryLine)
		.filter((entry): entry is FileEntry => entry !== null);
}

async function readEntryFromFileTail(filePath: string, entryId: string): Promise<SessionEntry | undefined> {
	const handle = await open(filePath, "r");
	try {
		const fileSize = (await handle.stat()).size;
		let position = fileSize;
		let leadingFragment = Buffer.alloc(0);

		while (position > 0) {
			const readSize = Math.min(SESSION_TAIL_READ_BUFFER_SIZE, position);
			position -= readSize;
			const chunk = Buffer.allocUnsafe(readSize);
			const { bytesRead } = await handle.read(chunk, 0, readSize, position);
			const data = Buffer.concat([chunk.subarray(0, bytesRead), leadingFragment]);
			let complete = data;

			if (position > 0) {
				const firstNewline = data.indexOf(0x0a);
				if (firstNewline === -1) {
					leadingFragment = data;
					continue;
				}
				leadingFragment = data.subarray(0, firstNewline);
				complete = data.subarray(firstNewline + 1);
			}

			const lines = complete.toString("utf8").split("\n");
			for (let index = lines.length - 1; index >= 0; index--) {
				const candidate = parseSessionEntryLine(lines[index]);
				if (candidate?.type !== "session" && candidate?.id === entryId) return candidate;
			}
		}
		return undefined;
	} finally {
		await handle.close();
	}
}

function readFirstLine(fd: number): string | null {
	const decoder = new StringDecoder("utf8");
	const buffer = Buffer.allocUnsafe(4096);
	let pending = "";

	while (true) {
		const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
		if (bytesRead === 0) {
			break;
		}

		pending += decoder.write(buffer.subarray(0, bytesRead));
		const newlineIndex = pending.indexOf("\n");
		if (newlineIndex !== -1) {
			return pending.slice(0, newlineIndex);
		}
	}

	pending += decoder.end();
	return pending.length > 0 ? pending : null;
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const sourceStats = statSync(resolvedFilePath);
	const cachedEntries = readCachedSessionEntries(resolvedFilePath, sourceStats.mtimeMs, sourceStats.size);
	if (cachedEntries) {
		return cachedEntries;
	}

	const entries: FileEntry[] = [];
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(lineStart, newlineIndex));
				if (entry) entries.push(entry);
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) entries.push(finalEntry);
	} finally {
		closeSync(fd);
	}

	// Validate session header
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}

	writeSessionEntriesCache(resolvedFilePath, sourceStats.mtimeMs, sourceStats.size, entries);
	return entries;
}

function readSessionHeader(filePath: string): SessionHeader | null {
	try {
		const fd = openSync(filePath, "r");
		try {
			const firstLine = readFirstLine(fd);
			if (!firstLine) return null;
			const header = JSON.parse(firstLine) as Record<string, unknown>;
			if (header.type !== "session" || typeof header.id !== "string") {
				return null;
			}
			return header as unknown as SessionHeader;
		} finally {
			closeSync(fd);
		}
	} catch {
		return null;
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeader(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.map(({ path }) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getMessageActivityTime(entry: SessionMessageEntry): number | undefined {
	const message = entry.message;
	if (!isMessageWithContent(message)) return undefined;
	if (message.role !== "user" && message.role !== "assistant") return undefined;

	const msgTimestamp = (message as { timestamp?: number }).timestamp;
	if (typeof msgTimestamp === "number") {
		return msgTimestamp;
	}

	const t = new Date(entry.timestamp).getTime();
	return Number.isNaN(t) ? undefined : t;
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const resolvedFilePath = normalizePath(filePath);
		const stats = await stat(resolvedFilePath);
		const cachedInfo = await readCachedSessionInfo(resolvedFilePath, stats.mtimeMs, stats.size);
		if (cachedInfo) {
			return cachedInfo;
		}

		let header: SessionHeader | null = null;
		let messageCount = 0;
		let firstMessage = "";
		const allMessages: string[] = [];
		let name: string | undefined;
		let lastActivityTime: number | undefined;

		const rl = createInterface({
			input: createReadStream(resolvedFilePath, { encoding: "utf8" }),
			crlfDelay: Infinity,
		});

		for await (const line of rl) {
			const entry = parseSessionEntryLine(line);
			if (!entry) continue;

			if (!header) {
				if (entry.type !== "session") return null;
				header = entry;
				continue;
			}

			// Extract session name (use latest, including explicit clears)
			if (entry.type === "session_info") {
				name = entry.name?.trim() || undefined;
			}

			if (entry.type !== "message") continue;
			messageCount++;

			const activityTime = getMessageActivityTime(entry);
			if (typeof activityTime === "number") {
				lastActivityTime = Math.max(lastActivityTime ?? 0, activityTime);
			}

			const message = entry.message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			allMessages.push(textContent);
			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}
		}

		if (!header) return null;

		const cwd = typeof header.cwd === "string" ? header.cwd : "";
		const parentSessionPath = header.parentSession;
		const headerTime = typeof header.timestamp === "string" ? new Date(header.timestamp).getTime() : NaN;
		const modified =
			typeof lastActivityTime === "number" && lastActivityTime > 0
				? new Date(lastActivityTime)
				: !Number.isNaN(headerTime)
					? new Date(headerTime)
					: stats.mtime;

		const sessionInfo: SessionInfo = {
			path: resolvedFilePath,
			id: header.id,
			cwd,
			name,
			parentSessionPath,
			created: new Date(header.timestamp),
			modified,
			messageCount,
			firstMessage: firstMessage || "(no messages)",
			allMessagesText: allMessages.join(" "),
		};
		await writeSessionInfoCache(resolvedFilePath, stats.mtimeMs, stats.size, sessionInfo);
		return sessionInfo;
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race(inFlight);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export interface SessionDurabilityState {
	queuedOperations: 0 | 1;
	pendingEntries: number;
	pendingRevisions: number;
	backpressured: boolean;
	failed: boolean;
}

export class SessionPersistenceBackpressureError extends Error {
	constructor(limit: number) {
		super(`Session persistence queue reached its ${limit}-entry backpressure limit`);
		this.name = "SessionPersistenceBackpressureError";
	}
}

export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;
	private persistedEntryCount = 0;
	private requestedDurabilityRevision = 0;
	private durableRevision = 0;
	private rewriteRequested = false;
	private persistenceLoop: Promise<void> | undefined;
	private persistenceError: Error | undefined;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir && !existsSync(this.sessionDir)) {
			mkdirSync(this.sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this.setSessionFile(sessionFile);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this.assertPersistenceIdle("switch session files");
		this.sessionFile = resolvePath(sessionFile);
		if (existsSync(this.sessionFile)) {
			this.withSessionFileLock(() => {
				this.fileEntries = loadEntriesFromFile(this.sessionFile!);

				// If file was empty or corrupted (no valid header), truncate and start fresh
				// to avoid appending messages without a session header (which breaks the session)
				if (this.fileEntries.length === 0) {
					const explicitPath = this.sessionFile;
					this.newSession();
					this.sessionFile = explicitPath;
					this.rewriteFileUnlocked();
					this.flushed = true;
					this.persistedEntryCount = this.fileEntries.length;
					return;
				}

				const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
				this.sessionId = header?.id ?? createSessionId();

				if (migrateToCurrentVersion(this.fileEntries)) {
					this.rewriteFileUnlocked();
				}

				this._buildIndex();
				this.flushed = true;
				this.persistedEntryCount = this.fileEntries.length;
			});
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		this.assertPersistenceIdle("start a new session");
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = options?.timestamp ?? new Date().toISOString();
		if (Number.isNaN(Date.parse(timestamp))) throw new Error(`Invalid Session timestamp: ${timestamp}`);
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
			spawnedFrom: options?.spawnedFrom,
			spawnConfig: options?.spawnConfig,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;
		this.persistedEntryCount = 0;
		this.requestedDurabilityRevision = 0;
		this.durableRevision = 0;
		this.rewriteRequested = false;
		this.persistenceError = undefined;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private withSessionFileLock<T>(fn: () => T): T {
		if (!this.persist || !this.sessionFile) return fn();
		const release = acquireSessionFileLockSync(this.sessionFile);
		try {
			return fn();
		} finally {
			release();
		}
	}

	private rewriteFileUnlocked(): void {
		if (!this.persist || !this.sessionFile) return;
		writeEntriesAtomically(this.sessionFile, this.fileEntries);
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		const hasUserMessage = this.fileEntries.some((entry) =>
			entry.type === "message" ? entry.message.role === "user" : false,
		);
		if (!this.flushed && !hasUserMessage) return;
		this.requestPersistence(true);
	}

	private assertPersistenceIdle(operation: string): void {
		if (this.persistenceLoop || this.requestedDurabilityRevision !== this.durableRevision) {
			throw new Error(`Cannot ${operation} while session persistence is pending; await flush() first`);
		}
	}

	private requestPersistence(rewrite: boolean): void {
		if (!this.persist || !this.sessionFile) return;
		if (this.persistenceError) {
			throw this.persistenceError;
		}
		this.requestedDurabilityRevision++;
		this.rewriteRequested ||= rewrite;
		this.ensurePersistenceLoop();
	}

	private ensurePersistenceLoop(): void {
		if (this.persistenceLoop || this.persistenceError) return;
		this.persistenceLoop = new Promise<void>((resolveStart) => setImmediate(resolveStart))
			.then(() => this.drainPersistence())
			.catch((error) => {
				this.persistenceError = error instanceof Error ? error : new Error(String(error));
			})
			.finally(() => {
				this.persistenceLoop = undefined;
				if (!this.persistenceError && this.durableRevision < this.requestedDurabilityRevision) {
					this.ensurePersistenceLoop();
				}
			});
	}

	private async drainPersistence(): Promise<void> {
		while (this.durableRevision < this.requestedDurabilityRevision) {
			const targetRevision = this.requestedDurabilityRevision;
			const targetFile = this.sessionFile;
			const targetEntries = this.fileEntries;
			const targetEntryCount = targetEntries.length;
			const startIndex = this.persistedEntryCount;
			const rewrite = this.rewriteRequested || !this.flushed;
			this.rewriteRequested = false;

			if (!targetFile) {
				this.durableRevision = targetRevision;
				continue;
			}

			const release = await acquireSessionFileLock(targetFile);
			try {
				if (rewrite) {
					if (!this.flushed && (await pathExists(targetFile))) {
						const error = new Error(`Session file already exists: ${targetFile}`);
						(error as NodeJS.ErrnoException).code = "EEXIST";
						throw error;
					}
					await writeEntriesAtomicallyAsync(targetFile, targetEntries, targetEntryCount);
				} else if (startIndex < targetEntryCount) {
					await appendEntriesAsync(targetFile, targetEntries, startIndex, targetEntryCount);
				}
			} finally {
				await release();
			}

			if (targetFile !== this.sessionFile || targetEntries !== this.fileEntries) {
				throw new Error("Session changed while persistence was in progress");
			}
			this.flushed = true;
			this.persistedEntryCount = targetEntryCount;
			this.durableRevision = targetRevision;
		}
	}

	/** Wait until every currently queued entry is readable from the canonical JSONL. */
	async flush(): Promise<void> {
		while (this.persistenceLoop) {
			await this.persistenceLoop;
		}
		if (this.persistenceError) {
			throw this.persistenceError;
		}
		if (this.durableRevision < this.requestedDurabilityRevision) {
			this.ensurePersistenceLoop();
			return this.flush();
		}
	}

	getDurabilityState(): SessionDurabilityState {
		const pendingEntries = Math.max(0, this.fileEntries.length - this.persistedEntryCount);
		return {
			queuedOperations: this.persistenceLoop ? 1 : 0,
			pendingEntries,
			pendingRevisions: Math.max(0, this.requestedDurabilityRevision - this.durableRevision),
			backpressured: pendingEntries >= SESSION_PERSISTENCE_MAX_PENDING_ENTRIES,
			failed: this.persistenceError !== undefined,
		};
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	/** Return an entry only when it can be read back from the canonical JSONL. */
	async getPersistedEntry(entryId: string): Promise<SessionEntry | undefined> {
		if (!this.persist || !this.sessionFile || !this.flushed) {
			return undefined;
		}

		return readEntryFromFileTail(this.sessionFile, entryId);
	}

	_persist(): void {
		if (!this.persist || !this.sessionFile) return;

		const hasUserMessage = this.fileEntries.some((candidate) =>
			candidate.type === "message" ? candidate.message.role === "user" : false,
		);
		if (!this.flushed && !hasUserMessage) {
			return;
		}
		this.requestPersistence(!this.flushed);
	}

	private _appendEntry(entry: SessionEntry): void {
		if (this.persistenceError) {
			throw this.persistenceError;
		}
		if (
			this.persist &&
			this.fileEntries.length - this.persistedEntryCount >= SESSION_PERSISTENCE_MAX_PENDING_ENTRIES
		) {
			throw new SessionPersistenceBackpressureError(SESSION_PERSISTENCE_MAX_PENDING_ENTRIES);
		}
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		this._persist();
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
		summaryStats?: CompactionEntry["summaryStats"],
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			summaryStats,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: name.trim(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info entry.
		// Empty names explicitly clear the session title.
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info") {
				return entry.name?.trim() || undefined;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.unshift(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		return path;
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/** Replace the opaque Mortise host metadata on the session header. */
	setMortiseMetadata(metadata: Record<string, unknown>): void {
		if (this.persistenceError) throw this.persistenceError;
		const header = this.getHeader();
		if (!header) {
			throw new Error("Cannot update Mortise metadata: session header is missing");
		}
		header.mortise = { ...metadata };
		this._rewriteFile();
	}

	/** Persist an explicitly hidden internal Session without weakening ordinary draft publication. */
	async publishHiddenSession(): Promise<void> {
		if (!this.persist || !this.sessionFile) return;
		this.assertPersistenceIdle("publish a hidden Session");
		const header = this.getHeader();
		if (header?.mortise?.hidden !== true) {
			throw new Error("Header-only publication is restricted to explicitly hidden Sessions");
		}
		const release = await acquireSessionFileLock(this.sessionFile);
		try {
			if (await pathExists(this.sessionFile)) {
				const error = new Error(`Session file already exists: ${this.sessionFile}`);
				(error as NodeJS.ErrnoException).code = "EEXIST";
				throw error;
			}
			await writeEntriesAtomicallyAsync(this.sessionFile, this.fileEntries, this.fileEntries.length);
		} finally {
			await release();
		}
		this.flushed = true;
		this.persistedEntryCount = this.fileEntries.length;
		this.requestedDurabilityRevision = 0;
		this.durableRevision = 0;
	}

	/**
	 * Update host-owned projection fields against the latest canonical JSONL.
	 * The lock-scoped reread prevents a cold metadata writer from replacing
	 * entries appended by an active runtime after this manager was opened.
	 */
	async updateHostProjection(options: {
		metadata?: Record<string, unknown>;
		name?: string;
		customType?: string;
	}): Promise<void> {
		if (!this.persist || !this.sessionFile) {
			throw new Error("Cannot update an in-memory Session projection");
		}
		await this.flush();
		const release = await acquireSessionFileLock(this.sessionFile);
		let entries: FileEntry[] | undefined;
		try {
			const latest = await loadEntriesFromFileAsync(this.sessionFile);
			const header = latest.find((entry): entry is SessionHeader => entry.type === "session");
			if (!header) throw new Error("Cannot update Mortise metadata: session header is missing");
			if (header.id !== this.sessionId) {
				throw new Error(`Session identity changed while updating host projection: ${header.id}`);
			}
			if (options.metadata !== undefined) header.mortise = { ...options.metadata };

			const ids = new Set(
				latest.filter((entry): entry is SessionEntry => entry.type !== "session").map((entry) => entry.id),
			);
			let parentId =
				[...latest].reverse().find((entry): entry is SessionEntry => entry.type !== "session")?.id ?? null;
			if (options.name !== undefined) {
				const entry: SessionInfoEntry = {
					type: "session_info",
					id: generateId(ids),
					parentId,
					timestamp: new Date().toISOString(),
					name: options.name,
				};
				latest.push(entry);
				ids.add(entry.id);
				parentId = entry.id;
			}
			if (options.metadata !== undefined && options.customType) {
				latest.push({
					type: "custom",
					id: generateId(ids),
					parentId,
					timestamp: new Date().toISOString(),
					customType: options.customType,
					data: options.metadata,
				});
			}

			await writeEntriesAtomicallyAsync(this.sessionFile, latest, latest.length);
			entries = latest;
		} finally {
			await release();
		}

		this.fileEntries = entries!;
		this._buildIndex();
		this.flushed = true;
		this.persistedEntryCount = entries!.length;
		this.requestedDurabilityRevision = 0;
		this.durableRevision = 0;
		this.rewriteRequested = false;
		this.persistenceError = undefined;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(branchFromId: string | null, summary: string, details?: unknown, fromHook?: boolean): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		this.assertPersistenceIdle("create a branched session");
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map
		const pathWithoutLabels = path.filter((e) => e.type !== "label");

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this.persistedEntryCount = 0;
			this.requestedDurabilityRevision = 0;
			this.durableRevision = 0;
			this.rewriteRequested = false;
			this.persistenceError = undefined;
			this._buildIndex();

			// A branch containing a user message is already a canonical Session.
			// Header-only branches remain unpublished until a complete user message
			// is appended (or the explicit hidden-Session boundary is used).
			const hasUserMessage = this.fileEntries.some((e) => e.type === "message" && e.message.role === "user");
			if (hasUserMessage) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const resolvedPath = resolvePath(path);
		// Extract cwd from session header if possible, otherwise use process.cwd()
		const entries = loadEntriesFromFile(resolvedPath);
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
		const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		return new SessionManager(cwd, dir, resolvedPath, true);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd()): SessionManager {
		return new SessionManager(cwd, "", undefined, false);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): SessionManager {
		const resolvedSourcePath = resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = loadEntriesFromFile(resolvedSourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		writeFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`, { flag: "wx" });

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
		}

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries.filter((e) => e.isDirectory()).map((e) => join(sessionsDir, e.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}

	/**
	 * List Mortise-owned child tasks by the parent session ID recorded in spawnedFrom.
	 */
	static async listChildrenBySpawnedFrom(parentSessionId: string, sessionDir?: string): Promise<ChildSessionInfo[]> {
		const sessions = await SessionManager.listAll(sessionDir);
		const children: ChildSessionInfo[] = [];

		for (const info of sessions) {
			const header = readSessionHeader(info.path);
			if (!header || header.spawnedFrom !== parentSessionId) {
				continue;
			}
			const branch = SessionManager.open(info.path).getBranch();
			const messages = branch
				.filter((entry): entry is SessionMessageEntry => entry.type === "message")
				.map((entry) => entry.message);
			const lastMessage = messages.at(-1);
			const persistedClientMutationIds = messages.flatMap((message) =>
				message.role === "user" && typeof message.clientMutationId === "string" ? [message.clientMutationId] : [],
			);
			let lastAssistant: Extract<AgentMessage, { role: "assistant" }> | undefined;
			for (let index = messages.length - 1; index >= 0; index--) {
				const message = messages[index];
				if (message?.role === "assistant") {
					lastAssistant = message;
					break;
				}
			}
			const lastOutput = lastAssistant
				? (typeof lastAssistant.content === "string"
						? lastAssistant.content
						: lastAssistant.content
								.filter((part): part is TextContent => part.type === "text")
								.map((part) => part.text)
								.join("\n")
					).trim() || undefined
				: undefined;
			const history = messages.slice(-50).flatMap((message) => {
				const record = message as unknown as Record<string, unknown>;
				const content = record.content;
				const text = (
					typeof content === "string"
						? content
						: Array.isArray(content)
							? content
									.flatMap((part) => {
										if (!part || typeof part !== "object") return [];
										const candidate = part as Record<string, unknown>;
										return candidate.type === "text" && typeof candidate.text === "string"
											? [candidate.text]
											: [];
									})
									.join("\n")
							: ""
				).trim();
				if (!text) return [];
				return [
					{
						role: message.role,
						text: text.slice(0, 4000),
						...(typeof record.timestamp === "number" ? { timestamp: record.timestamp } : {}),
						...(typeof record.stopReason === "string" ? { stopReason: record.stopReason } : {}),
						...(typeof record.clientMutationId === "string" ? { clientMutationId: record.clientMutationId } : {}),
					},
				];
			});
			const status =
				lastMessage?.role === "assistant"
					? lastMessage.stopReason === "error"
						? "failed"
						: lastMessage.stopReason === "aborted" || lastMessage.stopReason === "toolUse"
							? "interrupted"
							: "completed"
					: "interrupted";
			children.push({
				...info,
				spawnedFrom: header.spawnedFrom,
				spawnConfig: header.spawnConfig,
				parentSessionPath: header.parentSession,
				status,
				lastOutput,
				persistedClientMutationIds,
				history,
			});
		}

		children.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return children;
	}
}
