export { WsRpcServer, type WsRpcServerOptions } from '@mortise/server-core/transport'
export { WsRpcClient, type WsRpcClientOptions } from '@mortise/server-core/transport'
export { buildClientApi, type ChannelMap, type ChannelMapEntry } from './build-api'
export { CHANNEL_MAP } from './channel-map'
export type { RpcServer, RpcClient, RequestContext, HandlerFn, EventSink } from '@mortise/server-core/transport'
