import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { buildPlaygroundUiInventory, UI_COVERAGE_SCHEMA } from './playground-ui-inventory'

function idFor(sourcePath: string, exportName: string): string {
  const slug = `${sourcePath}-${exportName}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  return `source-${slug}`
}

export async function generatePlaygroundUiCatalog(root = process.cwd()): Promise<number> {
  const inventory = await buildPlaygroundUiInventory(root)
  const entries = inventory.candidates.map(candidate => ({ ...candidate, id: idFor(candidate.sourcePath, candidate.exportName) }))
  const catalogPath = resolve(root, 'apps/electron/src/renderer/playground/registry/ui-catalog.generated.ts')
  await mkdir(dirname(catalogPath), { recursive: true })
  await writeFile(catalogPath, `// Generated by scripts/generate-playground-ui-catalog.ts. Do not edit manually.\nexport const uiCatalogEntries = ${JSON.stringify(entries, null, 2)} as const\n`, 'utf8')
  return entries.length
}

export async function bootstrapPlaygroundUiCoverage(root = process.cwd()): Promise<number> {
  const inventory = await buildPlaygroundUiInventory(root)
  const coveragePath = resolve(root, 'apps/electron/src/renderer/playground/ui-coverage.json')
  await writeFile(coveragePath, `${JSON.stringify({
    schema: UI_COVERAGE_SCHEMA,
    entries: inventory.candidates.map(candidate => ({
      sourcePath: candidate.sourcePath,
      exportName: candidate.exportName,
      exemption: { reason: 'Requires a dedicated production adapter or is represented by its parent scene.' },
    })),
  }, null, 2)}\n`, 'utf8')
  return inventory.candidates.length
}

if (import.meta.main) {
  const bootstrapCoverage = process.argv.includes('--bootstrap-coverage')
  const count = bootstrapCoverage
    ? await bootstrapPlaygroundUiCoverage()
    : await generatePlaygroundUiCatalog()
  process.stdout.write(bootstrapCoverage
    ? `Bootstrapped ${count} Playground UI coverage exemptions.\n`
    : `Generated ${count} Playground UI catalog entries.\n`)
}
