import * as React from 'react'
import { useTranslation } from 'react-i18next'
import type { ComponentEntry } from './types'
import { generateCallbackPage, resolveCallbackPageLocale, type AppType } from '@mortise/shared/auth/callback-page'

/**
 * Preview component that renders OAuth callback HTML in a sandboxed iframe.
 * The HTML is generated by the same function used in the actual OAuth flow,
 * allowing us to preview the success/error states without triggering real OAuth.
 */
function OAuthCallbackPreview({
  isSuccess,
  errorDetail,
  appType,
}: {
  isSuccess: boolean
  errorDetail?: string
  appType: AppType
}) {
  const { t, i18n } = useTranslation()
  const html = React.useMemo(() => {
    return generateCallbackPage({
      title: isSuccess ? t('playground.oauth.successTitle') : t('playground.oauth.failureTitle'),
      isSuccess,
      errorDetail,
      appType,
      locale: resolveCallbackPageLocale(i18n.language),
    })
  }, [isSuccess, errorDetail, appType, t, i18n])

  return (
    <iframe
      srcDoc={html}
      sandbox="allow-scripts"
      className="w-full h-full border-0"
      title={t('playground.oauth.iframeTitle')}
    />
  )
}

export const oauthComponents: ComponentEntry[] = [
  {
    id: 'oauth-callback',
    name: 'OAuth Callback Page',
    nameZh: 'OAuth 回调页面',
    category: 'OAuth',
    description: 'Page shown in browser after OAuth authorization redirect',
    descriptionZh: 'OAuth 授权重定向后在浏览器中显示的页面',
    component: OAuthCallbackPreview,
    layout: 'full',
    props: [
      {
        name: 'isSuccess',
        description: 'Whether authorization was successful',
        descriptionZh: '授权是否成功',
        control: { type: 'boolean' },
        defaultValue: true,
      },
      {
        name: 'appType',
        description: 'App type (electron or terminal)',
        descriptionZh: '应用类型（electron 或 terminal）',
        control: {
          type: 'select',
          options: [
            { label: 'Electron', value: 'electron' },
            { label: 'Terminal', value: 'terminal' },
          ],
        },
        defaultValue: 'electron',
      },
      {
        name: 'errorDetail',
        description: 'Error message (only shown when isSuccess is false)',
        descriptionZh: '错误消息（仅当 isSuccess 为 false 时显示）',
        control: { type: 'string', placeholder: 'Error message' },
        defaultValue: '',
      },
    ],
    variants: [
      // Success states
      {
        name: 'Success',
        nameZh: '成功',
        props: { isSuccess: true, appType: 'electron' },
      },
      // Error states
      {
        name: 'Error - Access Denied',
        nameZh: '错误 - 拒绝访问',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The user denied the authorization request.',
        },
      },
      {
        name: 'Error - Invalid Scope',
        nameZh: '错误 - 无效范围',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The requested scope is invalid or unknown.',
        },
      },
      {
        name: 'Error - Server Error',
        nameZh: '错误 - 服务器错误',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The authorization server encountered an unexpected condition.',
        },
      },
      {
        name: 'Error - Expired Token',
        nameZh: '错误 - 令牌已过期',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The authorization code has expired.',
        },
      },
      {
        name: 'Error - Generic',
        nameZh: '错误 - 通用',
        props: {
          isSuccess: false,
          appType: 'electron',
        },
      },
    ],
    mockData: () => ({
      isSuccess: true,
      appType: 'electron',
    }),
  },
]
