#!/usr/bin/env node

import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import type { ImagesModel } from "../src/types.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");
const OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1";

interface OpenRouterModelRecord {
	id: string;
	name: string;
	context_length?: number;
	architecture?: {
		input_modalities?: string[];
		output_modalities?: string[];
	};
	pricing?: {
		prompt?: string;
		completion?: string;
		input_cache_read?: string;
		input_cache_write?: string;
	};
}

const MODALITY_ORDER = {
	text: 0,
	image: 1,
} as const;

function normalizeModalities(modalities: ("text" | "image")[]): ("text" | "image")[] {
	return Array.from(new Set(modalities)).sort((left, right) => MODALITY_ORDER[left] - MODALITY_ORDER[right]);
}

function formatArray(values: string[]): string {
	return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

function formatCost(model: ImagesModel<"openrouter-images">): string {
	return [
		"\t\t\tcost: {",
		`\t\t\t\tinput: ${model.cost.input},`,
		`\t\t\t\toutput: ${model.cost.output},`,
		`\t\t\t\tcacheRead: ${model.cost.cacheRead},`,
		`\t\t\t\tcacheWrite: ${model.cost.cacheWrite},`,
		"\t\t\t},",
	].join("\n");
}

function formatImageModel(model: ImagesModel<"openrouter-images">): string {
	return [
		"\t\t" + `${JSON.stringify(model.id)}: {`,
		`\t\t\tid: ${JSON.stringify(model.id)},`,
		`\t\t\tname: ${JSON.stringify(model.name)},`,
		`\t\t\tapi: ${JSON.stringify(model.api)},`,
		`\t\t\tprovider: ${JSON.stringify(model.provider)},`,
		`\t\t\tbaseUrl: ${JSON.stringify(model.baseUrl)},`,
		`\t\t\tinput: ${formatArray(model.input)},`,
		`\t\t\toutput: ${formatArray(model.output)},`,
		formatCost(model),
		'\t\t} satisfies ImagesModel<"openrouter-images">,',
	].join("\n");
}

async function fetchOpenRouterImageModels(): Promise<ImagesModel<"openrouter-images">[]> {
	try {
		console.log("Fetching image models from OpenRouter API...");
		const response = await fetch(`${OPENROUTER_BASE_URL}/models?output_modalities=image`);
		const data = (await response.json()) as { data?: OpenRouterModelRecord[] };
		const models: ImagesModel<"openrouter-images">[] = [];

		for (const model of data.data ?? []) {
			const input = normalizeModalities(
				(model.architecture?.input_modalities ?? []).filter(
					(modality): modality is "text" | "image" => modality === "text" || modality === "image",
				),
			);
			const output = normalizeModalities(
				(model.architecture?.output_modalities ?? []).filter(
					(modality): modality is "text" | "image" => modality === "text" || modality === "image",
				),
			);

			if (!output.includes("image")) continue;
			if (input.length === 0) input.push("text");

			models.push({
				id: model.id,
				name: model.name,
				api: "openrouter-images",
				provider: "openrouter",
				baseUrl: OPENROUTER_BASE_URL,
				input,
				output,
				cost: {
					input: parseFloat(model.pricing?.prompt || "0") * 1_000_000,
					output: parseFloat(model.pricing?.completion || "0") * 1_000_000,
					cacheRead: parseFloat(model.pricing?.input_cache_read || "0") * 1_000_000,
					cacheWrite: parseFloat(model.pricing?.input_cache_write || "0") * 1_000_000,
				},
			});
		}

		console.log(`Fetched ${models.length} image models from OpenRouter`);
		return models;
	} catch (error) {
		console.error("Failed to fetch OpenRouter image models:", error);
		return [];
	}
}

function generateImageModelsFile(models: ImagesModel<"openrouter-images">[]): string {
	const modelEntries = models
		.sort((left, right) => left.id.localeCompare(right.id))
		.map((model) => formatImageModel(model))
		.join("\n");

	return `// This file is auto-generated by scripts/generate-image-models.ts
// Do not edit manually - run 'npm run generate-image-models' to update

import type { ImagesApi, ImagesModel } from "./types.ts";

export const IMAGE_MODELS = {
\topenrouter: {
${modelEntries}
\t},
} as const satisfies Record<string, Record<string, ImagesModel<ImagesApi>>>;
`;
}

async function main(): Promise<void> {
	const models = await fetchOpenRouterImageModels();
	const output = generateImageModelsFile(models);
	const outputPath = join(packageRoot, "src", "image-models.generated.ts");
	const currentOutput = readFileSync(outputPath, "utf-8");
	if (currentOutput === output) {
		console.log(`No changes in ${outputPath}`);
		return;
	}
	writeFileSync(outputPath, output, "utf-8");
	console.log(`Generated ${outputPath}`);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
